# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essays', models.ManyToManyField(to='internal.EssayFill')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.Request')),
            ],
        ),
    ]
