# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfill',
            name='chosen',
            field=models.IntegerField(default=1),
        ),
    ]
