# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayMethodParameterFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('uncertainty', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='essaymethodparameter',
            name='uncertainty',
        ),
        migrations.RemoveField(
            model_name='essaymethodparameter',
            name='value',
        ),
        migrations.AddField(
            model_name='essaymethodparameterfill',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.EssayMethodParameter'),
        ),
    ]
