# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='expected_duration',
            field=models.IntegerField(default=10),
        ),
    ]
