# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='code',
            field=models.CharField(default='#######', max_length=10),
        ),
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(default='Insertar nombre de muestra', max_length=50),
        ),
    ]
