# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_sampletype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
