# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20170605_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaymethodfill',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
