# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20170530_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtemplate',
            name='essay_template',
        ),
        migrations.AddField(
            model_name='essaytemplate',
            name='tests',
            field=models.ManyToManyField(to='internal.TestTemplate'),
        ),
    ]
