# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_servicerequest_expected_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
