# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20170614_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
