# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_inventoryitem_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaymethodparameterfill',
            name='uncertainty',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='essaymethodparameterfill',
            name='value',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
