# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 02:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internal', '0003_auto_20170526_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='essay testing', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EssayTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('test_number', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Empty field', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SampleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('parameters_number', models.IntegerField(default=0)),
                ('essay_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.EssayTemplate')),
            ],
        ),
        migrations.RenameModel(
            old_name='Sample',
            new_name='SampleFill',
        ),
        migrations.DeleteModel(
            name='EssayType',
        ),
        migrations.RemoveField(
            model_name='samplefill',
            name='sampleType',
        ),
        migrations.DeleteModel(
            name='sampleType',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='samplefill',
            old_name='request',
            new_name='request_fill',
        ),
        migrations.RemoveField(
            model_name='testfill',
            name='request',
        ),
        migrations.RemoveField(
            model_name='testfill',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='testfill',
            name='testType',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userDescription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testfill',
            name='description',
            field=models.CharField(default='descripcion', max_length=100),
        ),
        migrations.AddField(
            model_name='parametertemplate',
            name='test_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.TestTemplate'),
        ),
        migrations.AddField(
            model_name='parameterfill',
            name='parameter_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.ParameterTemplate'),
        ),
        migrations.AddField(
            model_name='parameterfill',
            name='test_fill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.TestFill'),
        ),
        migrations.AddField(
            model_name='essayfill',
            name='essay_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.EssayTemplate'),
        ),
        migrations.AddField(
            model_name='samplefill',
            name='sample_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.SampleTemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testfill',
            name='essay_fill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.EssayFill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testfill',
            name='test_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.TestTemplate'),
            preserve_default=False,
        ),
    ]
