# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_auto_20170601_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayfill',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.EssayFillStatus'),
            preserve_default=False,
        ),
    ]
