# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_auto_20170601_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essaytemplate',
            name='tests',
        ),
        migrations.AddField(
            model_name='testtemplate',
            name='essays',
            field=models.ManyToManyField(related_name='tests', to='internal.EssayTemplate'),
        ),
    ]
