# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_auto_20170601_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtemplate',
            name='essays',
            field=models.ManyToManyField(blank=True, related_name='tests', to='internal.EssayTemplate'),
        ),
    ]
