# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_servicerequest_external_provider'),
        ('internal', '0004_auto_20170615_1932'),
    ]

    operations = [
    ]
