# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_auto_20170527_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('lab_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.LaboratoryType')),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('lab_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.LaboratoryType')),
            ],
        ),
        migrations.AddField(
            model_name='testtype',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtype',
            name='assay_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.EssayType'),
            preserve_default=False,
        ),
    ]
