# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_auto_20170605_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaymethodparameterfill',
            name='essay_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='internal.EssayMethodFill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essaymethodfill',
            name='essay_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_methods', to='internal.EssayMethod'),
        ),
    ]
