# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_auto_20170527_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestType',
        ),
    ]
