# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_auto_20170528_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtype',
            name='assay_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='internal.EssayType'),
        ),
    ]
