# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_merge_20170615_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('slug', models.CharField(max_length=30)),
                ('value', models.PositiveIntegerField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.ServiceRequestPriority'),
        ),
    ]
