# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_auto_20170528_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='laboratory',
        ),
        migrations.AddField(
            model_name='user',
            name='laboratory',
            field=models.ManyToManyField(to='internal.Laboratory'),
        ),
    ]
