# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_auto_20170605_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='observations',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
