# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0006_auto_20170606_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_essay_methods',
            field=models.ManyToManyField(blank=True, related_name='employees', to='internal.EssayMethodFill'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='essay_methods',
            field=models.ManyToManyField(blank=True, related_name='employees', to='internal.EssayMethod'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='essay_methods',
            field=models.ManyToManyField(blank=True, related_name='essays', to='internal.EssayMethod'),
        ),
        migrations.AlterField(
            model_name='essaymethod',
            name='parameters',
            field=models.ManyToManyField(blank=True, related_name='essaymethods', to='internal.EssayMethodParameter'),
        ),
        migrations.AlterField(
            model_name='essaymethodfill',
            name='external_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.ExternalProvider'),
        ),
        migrations.AlterField(
            model_name='essaymethodfill',
            name='inventory_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.InventoryOrder'),
        ),
        migrations.AlterField(
            model_name='externalprovider',
            name='services',
            field=models.ManyToManyField(blank=True, to='internal.ExternalProviderService'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='laboratories', to='internal.Employee'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='essay_methods',
            field=models.ManyToManyField(blank=True, related_name='laboratories', to='internal.EssayMethod'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='laboratories', to='internal.Inventory'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.Employee'),
        ),
    ]
