# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0006_auto_20170528_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaytype',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='assay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.EssayType'),
        ),
    ]
