# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_auto_20170606_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorder',
            name='pendiente',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
