# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_auto_20170616_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaymethod',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
