# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_auto_20170606_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaymethod',
            name='sample_types',
            field=models.ManyToManyField(blank=True, related_name='essay_methods', to='internal.SampleType'),
        ),
    ]
