# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_auto_20170601_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numEnsayo', models.IntegerField()),
                ('muestra', models.CharField(max_length=100)),
                ('tipoMuestra', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('pendiente', models.BooleanField()),
                ('aprobado', models.BooleanField()),
            ],
        ),
    ]
