# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0008_auto_20170616_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
