# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0008_inventoryorder_pendiente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryorder',
            old_name='pendiente',
            new_name='unsettled',
        ),
        migrations.AddField(
            model_name='sample',
            name='settled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
