# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0008_essaymethod_sample_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaymethodfill',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.Sample'),
            preserve_default=False,
        ),
    ]
