# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0008_requeststorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststorage',
            name='idSolicitud',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
