# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0009_requeststorage_idsolicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requeststorage',
            old_name='idSolicitud',
            new_name='idRequestStorage',
        ),
    ]
