# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0009_auto_20170607_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='settled',
        ),
    ]
