# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0010_remove_essaymethodfill_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayfill',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_fills', to='internal.Quotation'),
        ),
    ]
