# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0010_auto_20170601_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requeststorage',
            name='idRequestStorage',
        ),
    ]
