# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0010_remove_sample_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(default='muestra aleatoria 1', max_length=100),
            preserve_default=False,
        ),
    ]
