# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0011_remove_requeststorage_idrequeststorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststorage',
            name='idRequestStorage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
