# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0011_essayfill_quotation'),
    ]

    operations = [
    ]
