# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0011_auto_20170621_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='service_hours',
        ),
        migrations.DeleteModel(
            name='LaboratoryServiceHours',
        ),
    ]
