# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0011_sample_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.AddField(
            model_name='essayfill',
            name='quantity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sample',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='internal.Sample'),
            preserve_default=False,
        ),
    ]
