# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_auto_20170607_2256'),
        ('internal', '0012_essaymethodfill_chosen'),
    ]

    operations = [
    ]
