# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0012_auto_20170621_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='articleinventory',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('SupplyInventory', 'Insumos'), ('EquipmentInventory', 'Equipos')], default='SupplyInventory', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryarticle',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
