# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0012_auto_20170607_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='name',
        ),
    ]
