# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0013_auto_20170621_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('SupplyInventory', 'Insumos'), ('EquipmentInventory', 'Equipos'), ('SampleInventory', 'Muestras')], default='SupplyInventory', max_length=50),
        ),
    ]
