# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0013_merge_20170608_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaymethodfill',
            name='essay_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_methods', to='internal.EssayMethod'),
        ),
    ]
