# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0013_remove_inventoryitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory',
        ),
    ]
