# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0014_auto_20170608_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
