# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0015_remove_inventoryitem_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='sample',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='internal.Sample'),
            preserve_default=False,
        ),
    ]
