# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0015_servicerequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.ServiceRequestState'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.Employee'),
            preserve_default=False,
        ),
    ]
