# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0016_auto_20170626_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='internal.Laboratory'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_lab', to='internal.Employee'),
        ),
    ]
