# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0017_auto_20170628_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraRequestConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_concepts', to='internal.ServiceRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
