# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0018_extrarequestconcept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrarequestconcept',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_concepts', to='internal.Quotation'),
        ),
    ]
