# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0019_auto_20170629_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='observations',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
