# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0020_quotation_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrarequestconcept',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
