# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0021_extrarequestconcept_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internal.ServiceRequest'),
        ),
    ]
