# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0023_auto_20170629_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequeststate',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequeststate',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
