# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0024_auto_20170630_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayfill',
            name='observations',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='essaymethod',
            name='acreditado',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='essaymethodfill',
            name='observations',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='observations',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
