# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0025_auto_20170630_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletype',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
