# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0026_auto_20170630_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryarticle',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
