# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0027_auto_20170630_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('SupplyInventory', 'Insumos'), ('EquipmentInventory', 'Equipos')], default='SupplyInventory', max_length=50),
        ),
    ]
