# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0028_auto_20170702_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='doc_number',
            field=models.CharField(max_length=20),
        ),
    ]
